baseurl = "https://kaitlinnewson.com"
languageCode = "en-us"
title = "Kaitlin Newson"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-52735236-1"

[Params]
  subtitle = "Digital Projects Librarian <br> Toronto, ON"
  logo = "img/avatar.png"
  favicon = "img/favicon.ico"
  commit = false
  copyright = 2017

[Author]
  name = "Kaitlin Newson"
  email = "kaitlin@scholarsportal.info"
  github = "kaitlinnewson"
  twitter = "kaitlinnewson"
  linkedin = "kaitlinnewson"
  instagram = "librarypixels"
  spotify = "librarypixels"

## To be added back in later
## [[menu.main]]
##    name = "Blog"
##    url = "/"
##    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/page/projects/"
    weight = 1

[[menu.main]]
    name = "Resume"
    url = "/page/resume/"
    weight = 2
