baseurl = "https://kaitlinnewson.com"
title = "Kaitlin Newson"
theme = "jane"
enableRobotsTXT = true
googleAnalytics = "UA-52735236-1"
paginate = 3
defaultContentLanguage = "en"
hasCJKLanguage = false

[author]
    name = "Kaitlin"


[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Work"
    identifier = "work"
    url = "/page/work/"
    weight = 2
[[menu.main]]
    name = "CV"
    identifier = "cv"
    url = "/page/cv/"
    weight = 3

[params]
  subtitle = "Digital Projects Librarian <br> Toronto, ON"
  logoTitle = "Kaitlin Newson"
  favicon = "img/favicon.ico"
  dateFormatToUse = "2006-01-02"
  name = "Kaitlin Newson"

  customCSS = ['custom.css']
  customJS = []

   moreMeta = true

    [params.social]
        a-email = "kaitlin@scholarsportal.info"
        g-github = "kaitlinnewson"
        c-twitter = "kaitlinnewson"
        e-linkedin = "kaitlinnewson"
        m-instagram = "librarypixels"